[EMC]
VERSION = 1.1
MACHINE = Dino Evo Probe Basic
DEBUG = 0

[DISPLAY]
DISPLAY = probe_basic_lathe
BACK_TOOL_LATHE = 1
MASTER_TOOL_OFFSET_MODE = true
CONFIRM_EXIT = False
LOG_FILE = sim.log
LOG_LEVEL = INFO
PREFERENCE_FILE = sim.pref
CONFIG_FILE = custom_config.yml
CYCLE_TIME = 0.100
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
DEFAULT_LINEAR_VELOCITY = 6.000000
MAX_LINEAR_VELOCITY = 45.000000
MIN_LINEAR_VELOCITY = 0.500000
DEFAULT_ANGULAR_VELOCITY = 12.000000
MAX_ANGULAR_VELOCITY = 180.000000
MIN_ANGULAR_VELOCITY = 1.666667
DEFAULT_SPINDLE_SPEED = 300
MAX_SPINDLE_OVERRIDE = 1.000000
MIN_SPINDLE_OVERRIDE = 0.500000
MAX_FEED_OVERRIDE = 2.000000
PROGRAM_PREFIX = /home/evo/linuxcnc/nc_files
OPEN_FILE = /home/evo/linuxcnc/nc_files/pb_examples/blank.ngc
INTRO_GRAPHIC = pbsplash.png
INTRO_TIME = 3
INCREMENTS = 5mm 1mm .5mm .1mm .05mm .01mm .005mm
USER_BUTTONS_PATH = user_buttons/
USER_DROS_PATH = user_dro_display/
DRO_DISPLAY = XZ
GEOMETRY = XZ
OFFSET_COLUMNS = XZ
TOOL_TABLE_COLUMNS = TXZIJDQR
KEYBOARD_JOG = true
KEYBOARD_JOG_SAFETY_OFF = false
LATHE = 1
EDITOR = gedit

[FILTER]
PROGRAM_EXTENSION = .nc,.txt,.tap Other NC files
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[RS274NGC]
PARAMETER_FILE = linuxcnc.var
RS274NGC_STARTUP_CODE = G21 G40 G90 G94 G97 G64 P0.025
SUBROUTINE_PATH = subroutines
ON_ABORT_COMMAND = O<on_abort> CALL

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
BASE_PERIOD = 100000
SERVO_PERIOD = 1000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[HMOT]
CARD0=hm2_7i92.0

[HAL]
HALFILE = Dino_Evo.hal
HALUI = halui
#POSTGUI_HALFILE = probe_basic_postgui_fix.hal

[HALUI]

[TRAJ]
AXES = 2
SPINDLES = 2
COORDINATES = X Z
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
DEFAULT_VELOCITY = 8.00
MAX_LINEAR_VELOCITY = 135.00
DEFAULT_ACCELERATION = 20.0
MAX_ACCELERATION = 20.0
NO_FORCE_HOMING = 0

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[KINS]
KINEMATICS = trivkins coordinates=xz
JOINTS = 2

[AXIS_X]
MIN_LIMIT = -600.0
MAX_LIMIT = 600.0
MAX_VELOCITY = 75.0
MAX_ACCELERATION = 2250.0

[JOINT_0]
TYPE = LINEAR
HOME = 0.0
MAX_VELOCITY = 75.0
MAX_ACCELERATION = 2250.0
BACKLASH = 0.000
INPUT_SCALE = 4000
OUTPUT_SCALE = 1.000
MIN_LIMIT = -600.0
MAX_LIMIT = 600.0
FERROR = 10.0
MIN_FERROR = 1.0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_USE_INDEX = NO
HOME_IGNORE_LIMITS = NO
HOME_SEQUENCE = 2
HOME_IS_SHARED = 1
STEPGEN_MAXVEL = 93.75
STEPGEN_MAXACCEL = 2812.50
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
DIRSETUP = 10000
DIRHOLD = 10000
STEPLEN = 5000
STEPSPACE = 5000
STEP_SCALE = -500.0

[AXIS_Z]
MIN_LIMIT = -1000.0
MAX_LIMIT = 1000.0
MAX_VELOCITY = 72.0
MAX_ACCELERATION = 1350.0

[JOINT_1]
TYPE = LINEAR
HOME = 0.0
MAX_VELOCITY = 72.0
MAX_ACCELERATION = 1350.0
BACKLASH = 0.000
INPUT_SCALE = 4000
OUTPUT_SCALE = 1.000
MIN_LIMIT = -1000.0
MAX_LIMIT = 1000.0
FERROR = 10.0
MIN_FERROR = 1.0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_USE_INDEX = NO
HOME_IGNORE_LIMITS = NO
HOME_SEQUENCE = 1
HOME_IS_SHARED = 1
STEPGEN_MAXVEL = 90.0
STEPGEN_MAXACCEL = 1687.5
P = 1000.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1.0
FF2 = 0.0
BIAS = 0.0
DEADBAND = 0.0
MAX_OUTPUT = 0.0
DIRSETUP = 20000
DIRHOLD = 20000
STEPLEN = 10000
STEPSPACE = 10000
STEP_SCALE = -500.0

[SPINDLE_0]
P = 0
I = 0
D = 0
FF0 = 1
FF1 = 0
FF2 = 0
BIAS = 0
DEADBAND = 0
MAX_OUTPUT = 2000
