[env:octopus]
platform = ststm32
board = nucleo_f446ze
framework = arduino
upload_protocol = dfu
monitor_speed = 115200
board_build.core = stm32
board_upload.maximum_size = 524288
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_USE_CDC
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D USB_MANUFACTURER="CyberDino"
    -D USB_PRODUCT="FeedEncoder"
    -D HAL_PCD_MODULE_ENABLED
    -D HSE_VALUE=12000000U
