[env:octopus]
platform = ststm32
board = nucleo_f446ze
framework = arduino
upload_protocol = dfu
monitor_speed = 115200
build_flags =
    -D SERIAL_USB
    -D USBCON
    -D USB_MANUFACTURER="CyberDino"
    -D USB_PRODUCT="FeedEncoder"
    -D HAL_PCD_MODULE_ENABLED
